### ISSUE TITLE
Cool idea, upgrade to version `0xd`?

### ISSUE THREAD

**Issue by DougAnderson444** [Kylebrown9/template-compiler#1]
Hey I think this template idea is really cool. By rendering the HTML in a wasm sandbox the user doesn't need to be concerned about backdoor data removal off to some remote server.

I've following along the wit-bindgen progress and see that we've [gone from version `0xc` to `0xd`](https://github.com/bytecodealliance/wasm-tools/pull/1027) and wondered if this repo would work with the latest? A lot has changed in the past few months.

**Comment by DougAnderson444** [comment]
The answer:

![image](https://github.com/Kylebrown9/template-compiler/assets/6699901/1922f112-648a-4431-94d1-3778a0889f36)

I'll change the issue title to "Support version 0xd"

**Comment by esoterra** [comment]
I just tested upgrading all the dependencies and making a couple fix tweaks to the test `wit`s and the `wasm-encoder` apis, but there are some new validation rules that I need to figure out how to comply with.

Current WIP in #2.

**Comment by esoterra** [comment]
Resolved by #2
